"""empty message

Revision ID: 50e13d2a59db
Revises: 
Create Date: 2020-07-10 10:22:19.884458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e13d2a59db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('人员管理',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=12), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=12), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('人员管理')
    # ### end Alembic commands ###
