"""empty message

Revision ID: ecda71649234
Revises: 50e13d2a59db
Create Date: 2020-07-10 10:30:48.010645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecda71649234'
down_revision = '50e13d2a59db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('position', table_name='人员管理')
    op.drop_index('username', table_name='人员管理')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', '人员管理', ['username'], unique=True)
    op.create_index('position', '人员管理', ['position'], unique=True)
    # ### end Alembic commands ###
